language: go
sudo: false
go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - tip
cache:
  directories:
    - vendor
install:
  - npm i uber-licence
  - make dependencies
script:
  - make test
  - make lint
after_success:
  - make coveralls

